### ISSUE TITLE
Can I use prosemirror tables in prosemirror markdown?

### ISSUE THREAD

**Issue by EasonYou** [ProseMirror/prosemirror-tables#27]
Now I have a requirement in markdown like
|Tables         | Are           | Cool  |
| ------------- |:-------------:| -----:|
| col 3 is      | right-aligned | $1600 |
| col 2 is      | centered      |   $12 |
| zebra stripes | are neat      |    $1 |

parse it into a table

I try to mix them but it seems not to work.
I don't know if it can work together, can you tell me how to do?

**Comment by marijnh** [comment]
They don't work together by default. You might be able to get something to work if you set up the proper markdown parser and serializer logic, but you probably want a simpler table schema since Markdown doesn't allow as many shapes as this module does (merged cells, headers in arbitrary places, etc).

**Comment by eshvedai** [comment]
Try `markdown-it` with `markdown-it-table` plugin, it works for us pretty well.

**Comment by EasonYou** [comment]
@eshvedai emmmm... Your mean that I should choose another editor? But I need a WYSIWYN editor.

**Comment by keelii** [comment]
@eshvedai Could you show a demo code to explain how to use?

**Comment by nicholasmabrams** [comment]
@eshvedai I have taken your recommendation above about using `prosemirror-tables` with `prosemirror` in conjunction with `markdown-it` and `markdown-it-table` after hitting a dead end on going the prosemirror-markdown path. Unfortunately the approach I am using is not working. 

During testing I did the following hack, since the fromSchema.parse() method expects a DOM node.

`document.getElementById("editor").innerHTML = markdownIt.use(markdownItTable).render(document.createElement(''));` 

At this point console.log(document.getElementById("editor").innerHTML) shows correct transformation to HTML.

_Unfortunately, passing the updated node with updated contents does not cause the desired effect of loading the table with a table but instead grabs the markdown which gets replaced by  HTML from the step above._

`  let doc = DOMParser.fromSchema(schema).parse(document.querySelector("#content"))
  let state = EditorState.create({doc, plugins: exampleSetup({schema, menuContent: menu}).concat(
    columnResizing(),
    tableEditing(),
    keymap({
      "Tab": goToNextCell(1),
      "Shift-Tab": goToNextCell(-1)
    })
  )})`

Updating the editor node which originally contains MarkDown where it is then transformed into HTML and parsed by the code from your demo. I would love to eliminate the need to pass in the data with the HTML node and just pass the data to the parser directly. What am I missing? I am plugging away at it now, but any help would be greatly appreciated!
